### ISSUE TITLE
关于taxibj21

### ISSUE THREAD

**Issue by joynny** [jwwthu/DL4Traffic#1]
您好，我在您的论文中发现您提供一组新的北京人流预测数据TaxiBJ21。但是当我浏览您提供的github链接时却发现，该网址不存在。请问发生了什么事导致数据不可见。如果更新了数据提供地址，能否告知。

**Comment by jwwthu** [comment]
应该是文件夹的目录格式给错了，数据是这个工程的TaxiBJ21文件夹中的npy文件。
